### ISSUE TITLE
I cannot find anything in the documentation, how to build QVD from source code

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/git-qvd#1]
Hi,

I cannot find anything in the documentation, how to build QVD from the source code and neither can I find the source for i.a. the QVD Server Node and how to build it from source code.

Thank you in advance.

/Henrik

**Comment by vatral** [comment]
Hello,

Currently we lack official documentation on this. Our internal packaging system is targeted towards packaging not only QVD but also all of its dependencies, so that it should run pretty much everywhere. It requires some setup and is considerably more complicated than it should be for general use.

To actually get QVD working from source, though, all you need is to have all the needed dependencies, all of which can be found at CPAN. 

No compilation is needed, it's Perl so it can be run as-is from the tree, if you have all the dependencies in place.

Use the "run_client.sh" script found in the source repository. It will run the client from inside the tree if all the required packages are installed. It's likely you'll need to install packages from your repository or to use the cpan commandline tool. A similar approach will also work for VMA (VM agent, which runs inside the VM, and HKD (server daemon), except there's no script for that yet, but it's easy enough to see what needs to be done by looking at run_client.sh

**Comment by HenrikBach1** [comment]
Hi,

When running the run_client.sh found in the root of the tree of the source repository, it requires another script located in

./run_client.sh: line 25: /usr/lib/qvd/bin/perl: No such file or directory

What am I doing wrong?
