### ISSUE TITLE
Creation of packages of QVD

### ISSUE THREAD

**Issue by HenrikBach1** [theqvd/git-qvd#2]
Hi,

When running the run_client.sh found in the root of the tree of the source repository, it requires another script located in

./run_client.sh: line 25: /usr/lib/qvd/bin/perl: No such file or directory

What should I do?

**Comment by salva** [comment]
@HenrikBach1: it seems `run_client.sh` needs our own packed version of Perl that we use to run the QVD components, but don't worry, there are easier ways to run the different components of QVD directly from the git tree.

1. using the system `perl` or your own custom compiled version (for instance, using `perlbrew`), intall from CPAN the packages `lib::glob`, `perlrc` and `File::Tee`.

2. move into the `ext` subdirectory.

3. run the QVD programs preloading the `.perlrc` script using the `perlrc` module. For instance:

          perl -Mperlrc=. QVD-HKD/bin/hkd

It would fail, because of missing dependencies, just look at the errors an install then as they are reported. Debug files will appear in `/var/lib/qvd/tmp` or in `/tmp/qvd`.

Also, most QVD programs need to be run as root.

Besides that, you will have to create the PostgreSQL database as described in the documentation, set the connection parameters in `/etc/qvd/node.conf` and run the script at `QVD-DB/bin/qvd-db-deploy.pl` (also preloading `.perlrc`), and then create the bridge and configure the network and any other parameter you want to customize using the admin script at `QVD-Admin/bin/qvd-admin.pl`.
